"""update

Revision ID: 64e785d6fc71
Revises: 03c17fe801d7
Create Date: 2025-08-26 23:43:48.173674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64e785d6fc71'
down_revision = '03c17fe801d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    op.drop_table('projects')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('orders_ibfk_2'), 'projects', ['project_id'], ['project_id'])

    op.create_table('projects',
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('deadline', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('payment_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='projects_ibfk_1'),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('file_uploads',
    sa.Column('file_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('file_uploads_ibfk_1')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('file_uploads_ibfk_2')),
    sa.PrimaryKeyConstraint('file_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
