"""added changes

Revision ID: f6e40d9b44b0
Revises: a20e2fbf3ba4
Create Date: 2025-07-30 13:35:30.441724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e40d9b44b0'
down_revision = 'a20e2fbf3ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('price')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
